apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  labels:
    app: tito
  type: Opaque
  data:
  password: Vk13YXJlMSE=
  # Password created like this: echo -n 'VMware1!' | base64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titofe1
  labels:
    name: tito-fe
    version: "latest"
    app: tito
    tier: frontend
    stage: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      type: tito-fe
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tito
        type: tito-fe
        version: v1
        tier: frontend
    spec:
      containers:
        - name: tito
          image: adess/vmc-demo-k8s:v10
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: TITO_VERSION
            value: V2
          - name: TITO_SQL_SERVICE_SERVICE_HOST # The K8s DB
            value: tito-sql # the K8s DB
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: titofe-service
  labels:
    app: tito
    tier: frontend
    stage: prod
spec:
  type: LoadBalancer
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
  - port: 80
    targetPort: 80
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30007  
  selector:                
    type: tito-fe
    tier: frontend

    # the database deployed as service

---
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: titosql
        labels:
          name: tito-sql
          version: "latest"
          app: tito
          stage: prod
          tier: backend
      spec:
        replicas: 1
        minReadySeconds: 5
        strategy: 
          type: Recreate
        selector:
          matchLabels:
            tier: backend
            app: tito
        template:
          metadata:
            labels:
              tier: backend
              app: tito
          spec:
            containers:
            - name: tito-sql
              image: vmeoc/adess/tito-db
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 3306
              env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-pass
                    key: password