apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: ''
    repoURL: 'https://helm.elastic.co'
    targetRevision: 7.9.1
    chart: elasticsearch
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
source:
  repoURL: 'https://helm.elastic.co'
  targetRevision: 7.9.1
  helm:
    parameters:
      - name: antiAffinity
        value: soft
      - name: esJavaOpts
        value: '-Xmx128m -Xms128m'
      - name: resources.requests.cpu
        value: 100m
      - name: resources.requests.memory
        value: 512M
      - name: resources.limits.memory
        value: 2Gi
      - name: volumeClaimTemplate.storageClassName
        value: default
      - name: volumeClaimTemplate.resources.requests.storage
        value: 50Gi
  chart: elasticsearch
destination:
  server: 'https://kubernetes.default.svc'
  namespace: logs
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
