project: default
source:
  repoURL: 'https://helm.elastic.co'
  targetRevision: 7.9.1
  helm:
    parameters:
      - name: antiAffinity
        value: soft
      - name: esJavaOpts
        value: '-Xmx128m -Xms128m'
      - name: resources.requests.cpu
        value: 100m
      - name: resources.requests.memory
        value: 512M
      - name: resources.limits.memory
        value: 1Gi
      - name: volumeClaimTemplate.storageClassName
        value: default
      - name: volumeClaimTemplate.resources.requests.storage
        value: 40Gi
  chart: elasticsearch
destination:
  server: 'https://kubernetes.default.svc'
  namespace: logs
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
