apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
spec:
  destination:
    name: ''
    namespace: logs
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'c'
    targetRevision: 0.6.3
    chart: fluent-bit
    helm:
      parameters:
        - name: serviceMonitor.enabled
          value: 'false'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
