project: default
source:
  repoURL: 'https://fluent.github.io/helm-charts'
  targetRevision: 0.6.3
  chart: fluent-bit
destination:
  server: 'https://kubernetes.default.svc'
  namespace: logs
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
