project: default
source:
  repoURL: 'https://helm.elastic.co'
  targetRevision: 7.9.1
  helm:
    parameters:
      - name: ingress.enabled
        value: 'true'
      - name: 'ingress.hosts[0]'
        value: kibana.set.local
      - name: resources.requests.cpu
        value: 100m
      - name: resources.requests.memory
        value: 512M
  chart: kibana
destination:
  server: 'https://kubernetes.default.svc'
  namespace: logs
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
