apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tito-prod
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: tito-prod
    repoURL: 'https://github.com/appdess/vmworld2020'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
